"""
Forecast Model — MongoDB Document Schema

Collection: forecasts
Database: pahadpulse

Fields:
    _id          : ObjectId  — auto-generated by MongoDB
    product      : str       — name of the product (e.g. "Apples")
    market       : str       — local market name (e.g. "Mussoorie")
    demand_score : int       — predicted demand score (0–100)
    predicted_price : float  — predicted price in INR (₹)
"""

FORECAST_SCHEMA = {
    "product": str,
    "market": str,
    "demand_score": int,
    "predicted_price": float,
}
